# Logging for sql statements
#  https://www.baeldung.com/sql-logging-spring-boot#2-via-loggers
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://${DB_ADDRESS}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}